[package]
name = "kadium"
version = "1.2.3"
description = "App for YouTube upload notifications"
default-run = "kadium"
edition = "2018"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "1.0.0-rc.4", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { git = "https://github.com/tauri-apps/tauri", branch = "mac-app-hide", features = ["dialog-message", "notification-all", "shell-open"] }
rfd = "0.8.0"
atomicwrites = "0.3.0"
tokio = { version = "1.12.0", features = ["macros", "time", "sync"] }
reqwest = { version = "0.11.6", features = ["json"] }
sqlx = { version = "0.5.6", features = ["runtime-tokio-rustls", "sqlite"] }
chrono = "0.4.0"
iso8601-duration = "0.1.0"
url = "2.2.2"

[target.'cfg(target_os = "macos")'.dependencies]
macos-app-nap = "0.0.1"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
