name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            target: 'aarch64-apple-darwin'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            target: 'x86_64-apple-darwin'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-24.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            target: ''
            args: ''
          - platform: 'windows-latest'
            target: ''
            args: ''
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-24.04'
        shell: bash
        run: |
          sudo apt update;
          sudo apt install -y \
          build-essential \
          libgtk-3-dev \
          libssl-dev \
          libappindicator3-dev \
          librsvg2-dev patchelf;
          sudo apt install -y \
          libwebkit2gtk-4.1-0=2.44.0-2 \
          libwebkit2gtk-4.1-dev=2.44.0-2 \
          libjavascriptcoregtk-4.1-0=2.44.0-2 \
          libjavascriptcoregtk-4.1-dev=2.44.0-2 \
          gir1.2-javascriptcoregtk-4.1=2.44.0-2 \
          gir1.2-webkit2-4.1=2.44.0-2;

      - name: Install dependencies
        run: npm install

      - name: Build and release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: v__VERSION__
          releaseDraft: true
          args: ${{ matrix.target }}
